"""refactor code

Revision ID: 2962991fe014
Revises: 007e122e0ee0
Create Date: 2025-08-15 14:45:32.970213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2962991fe014'
down_revision: Union[str, Sequence[str], None] = '007e122e0ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_category_category_id', table_name='category')
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.drop_column('category', 'category_id')
    op.create_unique_constraint(None, 'product', ['id'])
    op.drop_constraint('product_subcategory_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product', 'subcategory', ['subcategory_id'], ['id'])
    op.add_column('subcategory', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'subcategory', ['id'])
    op.drop_constraint('subcategory_category_id_fkey', 'subcategory', type_='foreignkey')
    op.create_foreign_key(None, 'subcategory', 'category', ['category_id'], ['id'])
    op.drop_column('subcategory', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('subcategory_id', sa.INTEGER(), server_default=sa.text("nextval('subcategory_subcategory_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'subcategory', type_='foreignkey')
    op.create_foreign_key('subcategory_category_id_fkey', 'subcategory', 'category', ['category_id'], ['category_id'])
    op.drop_constraint(None, 'subcategory', type_='unique')
    op.drop_column('subcategory', 'id')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['category_id'])
    op.create_foreign_key('product_subcategory_id_fkey', 'product', 'subcategory', ['subcategory_id'], ['subcategory_id'])
    op.drop_constraint(None, 'product', type_='unique')
    op.add_column('category', sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.create_index('ix_category_category_id', 'category', ['category_id'], unique=False)
    op.drop_column('category', 'id')
    # ### end Alembic commands ###
