"""change column in user model

Revision ID: 2f2604e39a6e
Revises: c5a071ca633e
Create Date: 2025-09-28 19:35:21.080454

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2604e39a6e"
down_revision: str | Sequence[str] | None = "c5a071ca633e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("phone_number", sa.String(), nullable=True))
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "PhoneNumber")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("PhoneNumber", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
