"""add del_address

Revision ID: 3901611c7c20
Revises: 2f2604e39a6e
Create Date: 2025-10-20 19:03:52.028322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3901611c7c20'
down_revision: Union[str, Sequence[str], None] = '2f2604e39a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['id'])
    op.add_column('user', sa.Column('del_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'del_address')
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###