"""change db models

Revision ID: 8e14da57c5c1
Revises:
Create Date: 2025-08-14 16:58:52.518707

"""

from typing import Union

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8e14da57c5c1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
