"""add relationship order -> orderitem

Revision ID: 9e0f269bfbd1
Revises: ad429133c4fd
Create Date: 2025-08-27 17:58:48.744088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0f269bfbd1'
down_revision: Union[str, Sequence[str], None] = 'ad429133c4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_basket_id', table_name='basket')
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_column('orders', 'total_quantity')
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.add_column('orders', sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'order_id')
    op.create_index('ix_basket_id', 'basket', ['id'], unique=False)
    # ### end Alembic commands ###
