"""change model order

Revision ID: a7c312cd1055
Revises: 9e0f269bfbd1
Create Date: 2025-08-27 18:08:51.837864

"""

from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7c312cd1055"
down_revision: str | Sequence[str] | None = "9e0f269bfbd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_items", "order_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_unique_constraint(None, "product", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="unique")
    op.alter_column(
        "order_items", "order_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
