"""change user model

Revision ID: ad429133c4fd
Revises: b894c3980cc7
Create Date: 2025-08-24 16:49:27.628804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad429133c4fd"
down_revision: str | Sequence[str] | None = "b894c3980cc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_order_id_fkey", "user", type_="foreignkey")
    op.drop_column("user", "order_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key("user_order_id_fkey", "user", "orders", ["order_id"], ["id"])
    # ### end Alembic commands ###
