"""change user and basket model

Revision ID: b894c3980cc7
Revises: ceb9e34eea1f
Create Date: 2025-08-24 16:44:47.962413

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b894c3980cc7"
down_revision: str | Sequence[str] | None = "ceb9e34eea1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
