"""change user model

Revision ID: c5a071ca633e
Revises: c1876a49e085
Create Date: 2025-09-28 18:35:25.699863

"""

from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5a071ca633e"
down_revision: str | Sequence[str] | None = "c1876a49e085"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(), nullable=False))
    op.add_column("user", sa.Column("PhoneNumber", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "PhoneNumber")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
