"""change database models ALL

Revision ID: ceb9e34eea1f
Revises: c8bdde6deb37
Create Date: 2025-08-20 12:36:58.822937

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ceb9e34eea1f"
down_revision: str | Sequence[str] | None = "c8bdde6deb37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("basket_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "total_cost",
            sa.Float(),
            sa.Computed(
                "price*quantity",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["basket_id"],
            ["basket.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("basket_product_id_fkey", "basket", type_="foreignkey")
    op.drop_column("basket", "product_id")
    op.drop_column("basket", "quantity")
    op.drop_index("ix_category_id", table_name="category")
    op.drop_column("category", "description")
    op.add_column("orders", sa.Column("basket_id", sa.Integer(), nullable=False))
    op.add_column("orders", sa.Column("total_cost", sa.Float(), nullable=False))
    op.add_column("orders", sa.Column("total_quantity", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "orders", "basket", ["basket_id"], ["id"])
    op.drop_column("orders", "total_amount")
    op.alter_column(
        "product",
        "price",
        existing_type=sa.NUMERIC(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "product", ["id"])
    op.drop_constraint("product_category_id_fkey", "product", type_="foreignkey")
    op.drop_column("product", "category_id")
    op.drop_column("subcategory", "description")
    op.add_column("user", sa.Column("order_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "user", "orders", ["order_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "order_id")
    op.add_column(
        "subcategory",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "product",
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "product_category_id_fkey", "product", "category", ["category_id"], ["id"]
    )
    op.drop_constraint(None, "product", type_="unique")
    op.alter_column(
        "product",
        "price",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.add_column(
        "orders",
        sa.Column(
            "total_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "total_quantity")
    op.drop_column("orders", "total_cost")
    op.drop_column("orders", "basket_id")
    op.add_column(
        "category",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_category_id", "category", ["id"], unique=False)
    op.add_column(
        "basket",
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "basket",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "basket_product_id_fkey", "basket", "product", ["product_id"], ["id"]
    )
    op.drop_table("order_items")
    # ### end Alembic commands ###
