services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123456*@db:5432/mama_care_box
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456*
      - POSTGRES_DB=mama_care_box
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: